const otherSymptoms = [
	{ value: 'muscle_pain', label: 'Muscle pain' },
	{ value: 'excessive_hunger', label: 'Excessive hunger' },
	{ value: 'lethargy', label: 'Lethargy' },
	{ value: 'weight_loss', label: 'Weight loss' },
	{ value: 'breathlessness', label: 'Breathlessness' },
	{ value: 'phlegm', label: 'Phlegm' },
	{ value: 'mild_fever', label: 'Mild fever' },
	{ value: 'swelled_lymph_nodes', label: 'Swelled lymph nodes' },
	{
		value: 'blurred_and_distorted_vision',
		label: 'Blurred and distorted vision',
	},
	{ value: 'loss_of_balance', label: 'Loss of balance' },
	{ value: 'dizziness', label: 'Dizziness' },
	{ value: 'abnormal_menstruation', label: 'Abnormal menstruation' },
	{ value: 'muscle_weakness', label: 'Muscle weakness' },
	{ value: 'red_spots_over_body', label: 'Red spots over body' },
	{ value: 'fast_heart_rate', label: 'Fast heart rate' },
	{ value: 'depression', label: 'Depression' },
	{ value: 'mood_swings', label: 'Mood swings' },
	{ value: 'restlessness', label: 'Restlessness' },
	{ value: 'family_history', label: 'Family history' },
	{ value: 'neck_pain', label: 'Neck pain' },
	{ value: 'obesity', label: 'Obesity' },
	{ value: 'stiff_neck', label: 'Stiff neck' },
	{ value: 'painful_walking', label: 'Painful walking' },
	{ value: 'swelling_joints', label: 'Swelling joints' },
	{ value: 'constipation', label: 'Constipation' },
	{ value: 'back_pain', label: 'Back pain' },
	{ value: 'continuous_sneezing', label: 'Continuous sneezing' },
	{ value: 'stomach_pain', label: 'Stomach pain' },
	{ value: 'acidity', label: 'Acidity' },
	{ value: 'indigestion', label: 'Indigestion' },
	{ value: 'burning_micturition', label: 'Burning micturition' },
	{ value: 'redness_of_eyes', label: 'Redness of eyes' },
	{
		value: 'receiving_unsterile_injections',
		label: 'Receiving unsterile injections',
	},
	{
		value: 'receiving_blood_transfusion',
		label: 'Receiving blood transfusion',
	},
	{ value: 'throat_irritation', label: 'Throat irritation' },
	{ value: 'blood_in_sputum', label: 'Blood in sputum' },
	{ value: 'loss_of_smell', label: 'Loss of smell' },
	{ value: 'polyuria', label: 'Polyuria' },
	{ value: 'pain_behind_the_eyes', label: 'Pain behind the eyes' },
	{ value: 'swollen_extremeties', label: 'Swollen extremeties' },
	{ value: 'brittle_nails', label: 'Brittle nails' },
	{ value: 'increased_appetite', label: 'Increased appetite' },
	{ value: 'palpitations', label: 'Palpitations' },
	{ value: 'stomach_bleeding', label: 'Stomach bleeding' },
	{ value: 'congestion', label: 'Congestion' },
	{ value: 'enlarged_thyroid', label: 'Enlarged thyroid' },
	{ value: 'runny_nose', label: 'Runny nose' },
	{ value: 'coma', label: 'Coma' },
	{ value: 'slurred_speech', label: 'Slurred speech' },
	{ value: 'sinus_pressure', label: 'Sinus pressure' },
	{ value: 'rusty_sputum', label: 'Rusty sputum' },
	{ value: 'swelling_of_stomach', label: 'Swelling of stomach' },
	{ value: 'swollen_legs', label: 'Swollen legs' },
	{ value: 'skin_peeling', label: 'Skin peeling' },
	{ value: 'toxic_look_(typhos)', label: 'Toxic look (typhos)' },
	{ value: 'prominent_veins_on_calf', label: 'Prominent veins on calf' },
	{ value: 'unsteadiness', label: 'Unsteadiness' },
	{ value: 'red_sore_around_nose', label: 'Red sore around nose' },
	{ value: 'visual_disturbances', label: 'Visual disturbances' },
	{ value: 'small_dents_in_nails', label: 'Small dents in nails' },
	{ value: 'silver_like_dusting', label: 'Silver like dusting' },
	{ value: 'weight_gain', label: 'Weight gain' },
	{ value: 'yellow_crust_ooze', label: 'Yellow crust ooze' },
	{ value: 'passage_of_gases', label: 'Passage of gases' },
	{ value: 'puffy_face_and_eyes', label: 'Puffy face and eyes' },
	{ value: 'yellow_urine', label: 'Yellow urine' },
	{ value: 'pain_in_anal_region', label: 'Pain in anal region' },
	{
		value: 'history_of_alcohol_consumption',
		label: 'History of alcohol consumption',
	},
	{ value: 'continuous_feel_of_urine', label: 'Continuous feel of urine' },
	{ value: 'cramps', label: 'Cramps' },
	{ value: 'bloody_stool', label: 'Bloody stool' },
	{ value: 'blister', label: 'Blister' },
	{ value: 'bladder_discomfort', label: 'Bladder discomfort' },
	{ value: 'distention_of_abdomen', label: 'Distention of abdomen' },
	{ value: 'drying_and_tingling_lips', label: 'Drying and tingling lips' },
	{ value: 'belly_pain', label: 'Belly pain' },
	{ value: 'fluid_overload.1', label: 'Fluid overload.1' },
	{ value: 'bruising', label: 'Bruising' },
	{ value: 'hip_joint_pain', label: 'Hip joint pain' },
	{ value: 'anxiety', label: 'Anxiety' },
	{ value: 'inflammatory_nails', label: 'Inflammatory nails' },
	{ value: 'internal_itching', label: 'Internal itching' },
	{
		value: 'pain_during_bowel_movements',
		label: 'Pain during bowel movements',
	},
	{ value: 'acute_liver_failure', label: 'Acute liver failure' },
	{ value: 'mucoid_sputum', label: 'Mucoid sputum' },
	{ value: 'movement_stiffness', label: 'Movement stiffness' },
	{ value: 'altered_sensorium', label: 'Altered sensorium' },
	{ value: 'lack_of_concentration', label: 'Lack of concentration' },
	{ value: 'cold_hands_and_feets', label: 'Cold hands and feets' },
	{ value: 'knee_pain', label: 'Knee pain' },
	{ value: 'irritation_in_anus', label: 'Irritation in anus' },
	{ value: 'irregular_sugar_level', label: 'Irregular sugar level' },
	{ value: 'ulcers_on_tongue', label: 'Ulcers on tongue' },
	{ value: 'watering_from_eyes', label: 'Watering from eyes' },
	{ value: 'weakness_in_limbs', label: 'Weakness in limbs' },
	{ value: 'weakness_of_one_body_side', label: 'Weakness of one body side' },
	{ value: 'blackheads', label: 'Blackheads' },
	{ value: 'spotting_ urination', label: 'Spotting  urination' },
	{ value: 'swollen_blood_vessels', label: 'Swollen blood vessels' },
	{ value: 'sunken_eyes', label: 'Sunken eyes' },
	{ value: 'dehydration', label: 'Dehydration' },
	{ value: 'dischromic _patches', label: 'Dischromic  patches' },
	{ value: 'patches_in_throat', label: 'Patches in throat' },
	{ value: 'spinning_movements', label: 'Spinning movements' },
	{ value: 'extra_marital_contacts', label: 'Extra marital contacts' },
	{ value: 'shivering', label: 'Shivering' },
	{ value: 'scurring', label: 'Scurring' },
	{ value: 'pus_filled_pimples', label: 'Pus filled pimples' },
	{ value: 'nodal_skin_eruptions', label: 'Nodal skin eruptions' },
	{ value: 'muscle_wasting', label: 'Muscle wasting' },
	{ value: 'foul_smell_of urine', label: 'Foul smell of urine' },
	{ value: 'fluid_overload', label: 'Fluid overload' },
];

export default otherSymptoms;
