export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CART_GET_SHIPPING_ADDRESS_REQUEST =
	'CART_GET_SHIPPING_ADDRESS_REQUEST';
export const CART_GET_SHIPPING_ADDRESS_SUCCESS =
	'CART_GET_SHIPPING_ADDRESS_SUCCESS';
export const CART_GET_SHIPPING_ADDRESS_FAILURE =
	'CART_GET_SHIPPING_ADDRESS_FAILURE';

export const CART_UPDATE_SHIPPING_ADDRESS_REQUEST =
	'CART_UPDATE_SHIPPING_ADDRESS_REQUEST';
export const CART_UPDATE_SHIPPING_ADDRESS_SUCCESS =
	'CART_UPDATE_SHIPPING_ADDRESS_SUCCESS';
export const CART_UPDATE_SHIPPING_ADDRESS_FAILURE =
	'CART_UPDATE_SHIPPING_ADDRESS_FAILURE';

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
