export const GET_ALL_CONVERSATIONS_REQUEST = 'GET_ALL_CONVERSATIONS_REQUEST';
export const GET_ALL_CONVERSATIONS_SUCCESS = 'GET_ALL_CONVERSATIONS_SUCCESS';
export const GET_ALL_CONVERSATIONS_FAILURE = 'GET_ALL_CONVERSATIONS_FAILURE';
export const GET_ALL_CONVERSATIONS_RESET = 'GET_ALL_CONVERSATIONS_RESET';

export const GET_MESSAGES_OF_CONVERSATION_REQUEST =
	'GET_MESSAGES_OF_CONVERSATION_REQUEST';
export const GET_MESSAGES_OF_CONVERSATION_SUCCESS =
	'GET_MESSAGES_OF_CONVERSATION_SUCCESS';
export const GET_MESSAGES_OF_CONVERSATION_FAILURE =
	'GET_MESSAGES_OF_CONVERSATION_FAILURE';
export const GET_MESSAGES_OF_CONVERSATION_RESET =
	'GET_MESSAGES_OF_CONVERSATION_RESET';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
// export const SEND_MESSAGE_RESET = 'SEND_MESSAGE_RESET';
