export const GET_ALL_CONVERSATIONS_REQUEST = 'GET_ALL_CONVERSATIONS_REQUEST';
export const GET_ALL_CONVERSATIONS_SUCCESS = 'GET_ALL_CONVERSATIONS_SUCCESS';
export const GET_ALL_CONVERSATIONS_FAILURE = 'GET_ALL_CONVERSATIONS_FAILURE';
export const GET_ALL_CONVERSATIONS_RESET = 'GET_ALL_CONVERSATIONS_RESET';

// export const GET_CONVERSATION_MESSAGES_REQUEST =
// 	'GET_CONVERSATION_MESSAGES_REQUEST';
// export const GET_CONVERSATION_MESSAGES_SUCCESS =
// 	'GET_CONVERSATION_MESSAGES_SUCCESS';
// export const GET_CONVERSATION_MESSAGES_FAILURE =
// 	'GET_CONVERSATION_MESSAGES_FAILURE';
// export const GET_CONVERSATION_MESSAGES_RESET =
// 	'GET_CONVERSATION_MESSAGES_RESET';
