export const DOCTORS_LIST_REQUEST = 'DOCTORS_LIST_REQUEST';
export const DOCTORS_LIST_SUCCESS = 'DOCTORS_LIST_SUCCESS';
export const DOCTORS_LIST_FAILURE = 'DOCTORS_LIST_FAILURE';

export const GET_SINGLE_DOCTOR_REQUEST = 'GET_SINGLE_DOCTOR_REQUEST';
export const GET_SINGLE_DOCTOR_SUCCESS = 'GET_SINGLE_DOCTOR_SUCCESS';
export const GET_SINGLE_DOCTOR_FAILURE = 'GET_SINGLE_DOCTOR_FAILURE';
