export const REGISTER_DOCTOR_REQUEST = 'REGISTER_DOCTOR_REQUEST';
export const REGISTER_DOCTOR_SUCCESS = 'REGISTER_DOCTOR_SUCCESS';
export const REGISTER_DOCTOR_FAILURE = 'REGISTER_DOCTOR_FAILURE';

export const DOCTORS_LIST_REQUEST = 'DOCTORS_LIST_REQUEST';
export const DOCTORS_LIST_SUCCESS = 'DOCTORS_LIST_SUCCESS';
export const DOCTORS_LIST_FAILURE = 'DOCTORS_LIST_FAILURE';

export const GET_SINGLE_DOCTOR_REQUEST = 'GET_SINGLE_DOCTOR_REQUEST';
export const GET_SINGLE_DOCTOR_SUCCESS = 'GET_SINGLE_DOCTOR_SUCCESS';
export const GET_SINGLE_DOCTOR_FAILURE = 'GET_SINGLE_DOCTOR_FAILURE';

export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST';
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS';
export const PATIENTS_LIST_FAILURE = 'PATIENTS_LIST_FAILURE';

export const PATIENT_REQUEST_ACCEPTANCE_REQUEST =
	'PATIENT_REQUEST_ACCEPTANCE_REQUEST';
export const PATIENT_REQUEST_ACCEPTANCE_SUCCESS =
	'PATIENT_REQUEST_ACCEPTANCE_SUCCESS';
export const PATIENT_REQUEST_ACCEPTANCE_FAILURE =
	'PATIENT_REQUEST_ACCEPTANCE_FAILURE';
export const PATIENT_REQUEST_ACCEPTANCE_RESET =
	'PATIENT_REQUEST_ACCEPTANCE_RESET';
