export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE';

export const MY_ORDERS_LIST_REQUEST = 'MY_ORDERS_LIST_REQUEST';
export const MY_ORDERS_LIST_SUCCESS = 'MY_ORDERS_LIST_SUCCESS';
export const MY_ORDERS_LIST_FAILURE = 'MY_ORDERS_LIST_FAILURE';
export const MY_ORDERS_LIST_RESET = 'MY_ORDERS_LIST_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAILURE = 'ORDER_DELIVER_FAILURE';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const GET_ALL_ORDERS_ADMIN_REQUEST = 'GET_ALL_ORDERS_ADMIN_REQUEST';
export const GET_ALL_ORDERS_ADMIN_SUCCESS = 'GET_ALL_ORDERS_ADMIN_SUCCESS';
export const GET_ALL_ORDERS_ADMIN_FAILURE = 'GET_ALL_ORDERS_ADMIN_FAILURE';
// export const GET_ALL_ORDERS_ADMIN_RESET = 'GET_ALL_ORDERS_ADMIN_RESET';
