export const REQUEST_DOCTOR_CONTACT_REQUEST = 'REQUEST_DOCTOR_CONTACT_REQUEST';
export const REQUEST_DOCTOR_CONTACT_SUCCESS = 'REQUEST_DOCTOR_CONTACT_SUCCESS';
export const REQUEST_DOCTOR_CONTACT_FAILURE = 'REQUEST_DOCTOR_CONTACT_FAILURE';
export const REQUEST_DOCTOR_CONTACT_RESET = 'REQUEST_DOCTOR_CONTACT_RESET';
