export const REGISTER_PATIENT_REQUEST = 'REGISTER_PATIENT_REQUEST';
export const REGISTER_PATIENT_SUCCESS = 'REGISTER_PATIENT_SUCCESS';
export const REGISTER_PATIENT_FAILURE = 'REGISTER_PATIENT_FAILURE';

export const REQUEST_DOCTOR_CONTACT_REQUEST = 'REQUEST_DOCTOR_CONTACT_REQUEST';
export const REQUEST_DOCTOR_CONTACT_SUCCESS = 'REQUEST_DOCTOR_CONTACT_SUCCESS';
export const REQUEST_DOCTOR_CONTACT_FAILURE = 'REQUEST_DOCTOR_CONTACT_FAILURE';
export const REQUEST_DOCTOR_CONTACT_RESET = 'REQUEST_DOCTOR_CONTACT_RESET';

export const PATIENT_GET_ALL_REQUESTS_REQUEST =
	'PATIENT_GET_ALL_REQUESTS_REQUEST';
export const PATIENT_GET_ALL_REQUESTS_SUCCESS =
	'PATIENT_GET_ALL_REQUESTS_SUCCESS';
export const PATIENT_GET_ALL_REQUESTS_FAILURE =
	'PATIENT_GET_ALL_REQUESTS_FAILURE';
export const PATIENT_GET_ALL_REQUESTS_RESET = 'PATIENT_GET_ALL_REQUESTS_RESET';

export const GET_ACCEPTED_DOCTORS_REQUEST = 'GET_ACCEPTED_DOCTORS_REQUEST';
export const GET_ACCEPTED_DOCTORS_SUCCESS = 'GET_ACCEPTED_DOCTORS_SUCCESS';
export const GET_ACCEPTED_DOCTORS_FAILURE = 'GET_ACCEPTED_DOCTORS_FAILURE';
export const GET_ACCEPTED_DOCTORS_RESET = 'GET_ACCEPTED_DOCTORS_RESET';

export const GET_MEDICAL_INFO_REQUEST = 'GET_MEDICAL_INFO_REQUEST';
export const GET_MEDICAL_INFO_SUCCESS = 'GET_MEDICAL_INFO_SUCCESS';
export const GET_MEDICAL_INFO_FAILURE = 'GET_MEDICAL_INFO_FAILURE';
export const GET_MEDICAL_INFO_RESET = 'GET_MEDICAL_INFO_RESET';

export const UPDATE_MEDICAL_INFO_REQUEST = 'UPDATE_MEDICAL_INFO_REQUEST';
export const UPDATE_MEDICAL_INFO_SUCCESS = 'UPDATE_MEDICAL_INFO_SUCCESS';
export const UPDATE_MEDICAL_INFO_FAILURE = 'UPDATE_MEDICAL_INFO_FAILURE';
export const UPDATE_MEDICAL_INFO_RESET = 'UPDATE_MEDICAL_INFO_RESET';

export const GET_SINGLE_PATIENT_REQUEST = 'GET_SINGLE_PATIENT_REQUEST';
export const GET_SINGLE_PATIENT_SUCCESS = 'GET_SINGLE_PATIENT_SUCCESS';
export const GET_SINGLE_PATIENT_FAILURE = 'GET_SINGLE_PATIENT_FAILURE';
export const GET_SINGLE_PATIENT_RESET = 'GET_SINGLE_PATIENT_RESET';
