export const REGISTER_PATIENT_REQUEST = 'REGISTER_PATIENT_REQUEST';
export const REGISTER_PATIENT_SUCCESS = 'REGISTER_PATIENT_SUCCESS';
export const REGISTER_PATIENT_FAILURE = 'REGISTER_PATIENT_FAILURE';

export const REQUEST_DOCTOR_CONTACT_REQUEST = 'REQUEST_DOCTOR_CONTACT_REQUEST';
export const REQUEST_DOCTOR_CONTACT_SUCCESS = 'REQUEST_DOCTOR_CONTACT_SUCCESS';
export const REQUEST_DOCTOR_CONTACT_FAILURE = 'REQUEST_DOCTOR_CONTACT_FAILURE';
export const REQUEST_DOCTOR_CONTACT_RESET = 'REQUEST_DOCTOR_CONTACT_RESET';

export const PATIENT_GET_ALL_REQUESTS_REQUEST =
	'PATIENT_GET_ALL_REQUESTS_REQUEST';
export const PATIENT_GET_ALL_REQUESTS_SUCCESS =
	'PATIENT_GET_ALL_REQUESTS_SUCCESS';
export const PATIENT_GET_ALL_REQUESTS_FAILURE =
	'PATIENT_GET_ALL_REQUESTS_FAILURE';
export const PATIENT_GET_ALL_REQUESTS_RESET = 'PATIENT_GET_ALL_REQUESTS_RESET';
