export const LUNGS_PREDICTION_REQUEST = 'LUNGS_PREDICTION_REQUEST';
export const LUNGS_PREDICTION_SUCCESS = 'LUNGS_PREDICTION_SUCCESS';
export const LUNGS_PREDICTION_FAILURE = 'LUNGS_PREDICTION_FAILURE';
export const LUNGS_PREDICTION_RESET = 'LUNGS_PREDICTION_RESET';
