export const LUNGS_PREDICTION_REQUEST = 'LUNGS_PREDICTION_REQUEST';
export const LUNGS_PREDICTION_SUCCESS = 'LUNGS_PREDICTION_SUCCESS';
export const LUNGS_PREDICTION_FAILURE = 'LUNGS_PREDICTION_FAILURE';
export const LUNGS_PREDICTION_RESET = 'LUNGS_PREDICTION_RESET';

export const DISEASE_PREDICTION_REQUEST = 'DISEASE_PREDICTION_REQUEST';
export const DISEASE_PREDICTION_SUCCESS = 'DISEASE_PREDICTION_SUCCESS';
export const DISEASE_PREDICTION_FAILURE = 'DISEASE_PREDICTION_FAILURE';
export const DISEASE_PREDICTION_RESET = 'DISEASE_PREDICTION_RESET';
