export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';

export const PRODUCT_CREATE_ADMIN_REQUEST = 'PRODUCT_CREATE_ADMIN_REQUEST';
export const PRODUCT_CREATE_ADMIN_SUCCESS = 'PRODUCT_CREATE_ADMIN_SUCCESS';
export const PRODUCT_CREATE_ADMIN_FAILURE = 'PRODUCT_CREATE_ADMIN_FAILURE';
export const PRODUCT_CREATE_ADMIN_RESET = 'PRODUCT_CREATE_ADMIN_RESET';

export const PRODUCT_EDIT_ADMIN_REQUEST = 'PRODUCT_EDIT_ADMIN_REQUEST';
export const PRODUCT_EDIT_ADMIN_SUCCESS = 'PRODUCT_EDIT_ADMIN_SUCCESS';
export const PRODUCT_EDIT_ADMIN_FAILURE = 'PRODUCT_EDIT_ADMIN_FAILURE';
export const PRODUCT_EDIT_ADMIN_RESET = 'PRODUCT_EDIT_ADMIN_RESET';

export const PRODUCT_DELETE_ADMIN_REQUEST = 'PRODUCT_DELETE_ADMIN_REQUEST';
export const PRODUCT_DELETE_ADMIN_SUCCESS = 'PRODUCT_DELETE_ADMIN_SUCCESS';
export const PRODUCT_DELETE_ADMIN_FAILURE = 'PRODUCT_DELETE_ADMIN_FAILURE';
export const PRODUCT_DELETE_ADMIN_RESET = 'PRODUCT_DELETE_ADMIN_RESET';
