export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

// for getting user details
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILURE = 'USER_UPDATE_PROFILE_FAILURE';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const ALL_USERS_LIST_ADMIN_REQUEST = 'ALL_USERS_LIST_ADMIN_REQUEST';
export const ALL_USERS_LIST_ADMIN_SUCCESS = 'ALL_USERS_LIST_ADMIN_SUCCESS';
export const ALL_USERS_LIST_ADMIN_FAILURE = 'ALL_USERS_LIST_ADMIN_FAILURE';
export const ALL_USERS_LIST_ADMIN_RESET = 'ALL_USERS_LIST_ADMIN_RESET';

export const GET_SINGLE_USER_ADMIN_REQUEST = 'GET_SINGLE_USER_ADMIN_REQUEST';
export const GET_SINGLE_USER_ADMIN_SUCCESS = 'GET_SINGLE_USER_ADMIN_SUCCESS';
export const GET_SINGLE_USER_ADMIN_FAILURE = 'GET_SINGLE_USER_ADMIN_FAILURE';

export const EDIT_USER_ADMIN_REQUEST = 'EDIT_USER_ADMIN_REQUEST';
export const EDIT_USER_ADMIN_SUCCESS = 'EDIT_USER_ADMIN_SUCCESS';
export const EDIT_USER_ADMIN_FAILURE = 'EDIT_USER_ADMIN_FAILURE';
export const EDIT_USER_ADMIN_RESET = 'EDIT_USER_ADMIN_RESET';

export const DELETE_USER_ADMIN_REQUEST = 'DELETE_USER_ADMIN_REQUEST';
export const DELETE_USER_ADMIN_SUCCESS = 'DELETE_USER_ADMIN_SUCCESS';
export const DELETE_USER_ADMIN_FAILURE = 'DELETE_USER_ADMIN_FAILURE';
export const DELETE_USER_ADMIN_RESET = 'DELETE_USER_ADMIN_RESET';
